# image:
#    repository: registry.gitlab.factory.social.gouv.fr/socialgouv/docker/nginx4spa
#    tag: master

labels:
   app.kubernetes.io/part-of: medle
   owner: medle
   team: medle

deployment:
   annotations:
      app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}
      app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}

   port: 80

   livenessProbe:
      periodSeconds: 20
   readinessProbe:
      periodSeconds: 20

   resources:
      limits:
         memory: 128Mi
      requests:
         memory: 64Mi

   env:
      - name: PORT
        value: "80"
      - name: NODE_ENV
        value: "production"

ingress:
   enabled: true
   annotations:
      appgw.ingress.kubernetes.io/ssl-redirect: "true"
      kubernetes.io/ingress.class: "azure/application-gateway"
   hosts:
      - host: "medle.fabrique.social.gouv.fr"
        paths:
           - path: /
             servicePort: 80
   tls:
      - hosts:
           - "medle.fabrique.social.gouv.fr"
        secretName: wildcard-crt
